"""
Agentic Profile Matching — Phase 1 RAG Tests.

Tests for:
  1. PDF text extraction
  2. Text chunking (count, size, overlap)
  3. Vector store initialization and reset
  4. Full ingestion pipeline (directory -> ChromaDB)
  5. Semantic search returning correct candidates
  6. Full resume reassembly via get_full_resume
  7. Deduplication in search results
  8. Candidate ID listing
"""

from __future__ import annotations

import tempfile
from pathlib import Path

import pytest

from src.rag.indexer import ResumeIndexer
from src.rag.retriever import ResumeRetriever
from src.rag.store import get_vector_store, reset_collection

# Path to sample resumes generated by scripts/generate_sample_resumes.py
FIXTURES_DIR = Path(__file__).parent / "fixtures" / "sample_resumes"


# ===================================================================
# Fixtures
# ===================================================================


@pytest.fixture
def sample_pdf_path() -> Path:
    """Return path to the React developer resume."""
    path = FIXTURES_DIR / "Alice_Johnson_React_Developer.pdf"
    assert path.exists(), f"Missing test fixture: {path}"
    return path


@pytest.fixture
def all_sample_pdfs() -> list[Path]:
    """Return paths to all 4 sample resume PDFs."""
    pdfs = sorted(FIXTURES_DIR.glob("*.pdf"))
    assert len(pdfs) >= 4, f"Expected 4+ sample PDFs, found {len(pdfs)}"
    return pdfs


@pytest.fixture
def temp_chroma_dir(tmp_path: Path) -> Path:
    """Provide a temporary directory for ChromaDB data."""
    chroma_dir = tmp_path / "chroma_db"
    chroma_dir.mkdir()
    return chroma_dir


@pytest.fixture
def indexed_store(all_sample_pdfs: list[Path], temp_chroma_dir: Path) -> object:
    """Create a fully indexed ChromaDB collection with all sample resumes."""
    collection = reset_collection(temp_chroma_dir)
    indexer = ResumeIndexer(chunk_size=1000, chunk_overlap=200)
    stats = indexer.ingest_directory(FIXTURES_DIR, collection)
    assert stats["pdfs_processed"] >= 4
    return collection


@pytest.fixture
def retriever(indexed_store: object) -> ResumeRetriever:
    """Provide a ResumeRetriever backed by the indexed store."""
    return ResumeRetriever(indexed_store)


# ===================================================================
# 1. PDF Text Extraction Tests
# ===================================================================


class TestTextExtraction:
    def test_extract_text_from_pdf(self, sample_pdf_path: Path) -> None:
        """Verify PyMuPDF can extract text from a known sample PDF."""
        text = ResumeIndexer._extract_text(sample_pdf_path)
        assert isinstance(text, str)
        assert len(text) > 100, "Resume text too short — extraction may have failed"
        assert "Alice" in text or "ALICE" in text, "Expected candidate name not found"
        assert "React" in text, "Expected skill 'React' not found in extracted text"

    def test_extract_text_all_pdfs(self, all_sample_pdfs: list[Path]) -> None:
        """All sample PDFs should yield non-empty text."""
        for pdf_path in all_sample_pdfs:
            text = ResumeIndexer._extract_text(pdf_path)
            assert len(text) > 50, f"PDF {pdf_path.name} yielded too little text"

    def test_extract_nonexistent_pdf(self) -> None:
        """Extracting from a nonexistent path should raise an error."""
        with pytest.raises(Exception):
            ResumeIndexer._extract_text(Path("/nonexistent/resume.pdf"))


# ===================================================================
# 2. Text Chunking Tests
# ===================================================================


class TestChunking:
    def test_chunk_count(self, sample_pdf_path: Path) -> None:
        """A ~2000 char resume should produce multiple chunks."""
        text = ResumeIndexer._extract_text(sample_pdf_path)
        indexer = ResumeIndexer(chunk_size=500, chunk_overlap=100)
        chunks = indexer._chunk_text(text)
        # With ~2000 chars and 500 char chunks with 100 overlap (step=400),
        # we expect at least 3 chunks
        assert len(chunks) >= 3, f"Expected 3+ chunks, got {len(chunks)}"

    def test_chunk_size_respected(self, sample_pdf_path: Path) -> None:
        """No chunk should exceed chunk_size by more than a small margin."""
        text = ResumeIndexer._extract_text(sample_pdf_path)
        indexer = ResumeIndexer(chunk_size=1000, chunk_overlap=200)
        chunks = indexer._chunk_text(text)
        for chunk in chunks:
            assert len(chunk["text"]) <= 1050, (
                f"Chunk {chunk['index']} exceeds chunk_size: "
                f"{len(chunk['text'])} > 1050"
            )

    def test_chunk_indices_sequential(self, sample_pdf_path: Path) -> None:
        """Chunk indices should be 0, 1, 2, ... N-1."""
        text = ResumeIndexer._extract_text(sample_pdf_path)
        indexer = ResumeIndexer(chunk_size=500, chunk_overlap=100)
        chunks = indexer._chunk_text(text)
        indices = [c["index"] for c in chunks]
        assert indices == list(range(len(chunks)))

    def test_empty_text_returns_no_chunks(self) -> None:
        """Empty or whitespace-only text should return empty list."""
        indexer = ResumeIndexer()
        assert indexer._chunk_text("") == []
        assert indexer._chunk_text("   \n  ") == []

    def test_short_text_single_chunk(self) -> None:
        """Text shorter than chunk_size should produce exactly 1 chunk."""
        indexer = ResumeIndexer(chunk_size=1000, chunk_overlap=200)
        chunks = indexer._chunk_text("Hello, this is a short resume.")
        assert len(chunks) == 1


# ===================================================================
# 3. Vector Store Tests
# ===================================================================


class TestVectorStore:
    def test_get_vector_store_creates_collection(self, temp_chroma_dir: Path) -> None:
        """get_vector_store should create a ChromaDB collection."""
        collection = get_vector_store(temp_chroma_dir)
        assert collection is not None
        assert collection.name == "resumes"

    def test_get_vector_store_is_idempotent(self, temp_chroma_dir: Path) -> None:
        """Calling get_vector_store twice returns the same collection."""
        c1 = get_vector_store(temp_chroma_dir)
        c2 = get_vector_store(temp_chroma_dir)
        assert c1.name == c2.name
        assert c1.count() == c2.count()

    def test_reset_collection_clears_data(self, temp_chroma_dir: Path) -> None:
        """reset_collection should wipe all existing data."""
        collection = get_vector_store(temp_chroma_dir)
        # The collection is empty on fresh creation, so just verify reset works
        reset_collection(temp_chroma_dir)
        collection2 = get_vector_store(temp_chroma_dir)
        assert collection2.count() == 0


# ===================================================================
# 4. Full Ingestion Pipeline Tests
# ===================================================================


class TestIngestion:
    def test_ingest_directory_stats(self, temp_chroma_dir: Path) -> None:
        """Ingesting all sample PDFs should produce correct statistics."""
        collection = reset_collection(temp_chroma_dir)
        indexer = ResumeIndexer(chunk_size=1000, chunk_overlap=200)
        stats = indexer.ingest_directory(FIXTURES_DIR, collection)

        assert stats["pdfs_processed"] == 4
        assert stats["total_chunks"] > 0
        assert stats["collection_count"] == stats["total_chunks"]

    def test_ingest_nonexistent_directory(self, temp_chroma_dir: Path) -> None:
        """Ingesting a missing directory should raise FileNotFoundError."""
        collection = get_vector_store(temp_chroma_dir)
        indexer = ResumeIndexer()
        with pytest.raises(FileNotFoundError):
            indexer.ingest_directory("/nonexistent/directory", collection)

    def test_ingest_empty_directory(self, tmp_path: Path, temp_chroma_dir: Path) -> None:
        """Ingesting a directory with no PDFs should raise FileNotFoundError."""
        empty_dir = tmp_path / "empty_resumes"
        empty_dir.mkdir()
        collection = get_vector_store(temp_chroma_dir)
        indexer = ResumeIndexer()
        with pytest.raises(FileNotFoundError):
            indexer.ingest_directory(empty_dir, collection)


# ===================================================================
# 5. Semantic Search Tests
# ===================================================================


class TestSearch:
    def test_search_react_developer(
        self, retriever: ResumeRetriever, indexed_store: object
    ) -> None:
        """Search for 'React developer' should return Alice Johnson (React dev)."""
        results = retriever.search("React developer with 3 years experience", top_k=3)
        assert len(results) >= 1, "Search returned no results"
        names = [r["name"] for r in results]
        assert any("Alice" in n for n in names), (
            f"Expected Alice (React dev) in results, got: {names}"
        )

    def test_search_python_backend(
        self, retriever: ResumeRetriever, indexed_store: object
    ) -> None:
        """Search for 'Python backend' should return Bob Smith."""
        results = retriever.search("Python backend Django FastAPI engineer", top_k=3)
        assert len(results) >= 1
        names = [r["name"] for r in results]
        assert any("Bob" in n for n in names), (
            f"Expected Bob (Python backend) in results, got: {names}"
        )

    def test_search_data_scientist(
        self, retriever: ResumeRetriever, indexed_store: object
    ) -> None:
        """Search for 'data scientist machine learning' should return Carol."""
        results = retriever.search(
            "data scientist machine learning NLP neural networks", top_k=3
        )
        assert len(results) >= 1
        names = [r["name"] for r in results]
        assert any("Carol" in n for n in names), (
            f"Expected Carol (Data Scientist) in results, got: {names}"
        )

    def test_search_devops(
        self, retriever: ResumeRetriever, indexed_store: object
    ) -> None:
        """Search for 'DevOps Kubernetes' should return David."""
        results = retriever.search(
            "DevOps Kubernetes AWS cloud infrastructure engineer", top_k=3
        )
        assert len(results) >= 1
        names = [r["name"] for r in results]
        assert any("David" in n for n in names), (
            f"Expected David (DevOps) in results, got: {names}"
        )

    def test_search_returns_standardized_format(self, retriever: ResumeRetriever) -> None:
        """Each result should have the expected keys."""
        results = retriever.search("React developer", top_k=3)
        for r in results:
            assert "candidate_id" in r
            assert "name" in r
            assert "score" in r
            assert "excerpt" in r
            assert isinstance(r["score"], (int, float))

    def test_search_deduplication(self, retriever: ResumeRetriever) -> None:
        """Results should be deduplicated by candidate_id."""
        results = retriever.search("developer", top_k=10)
        candidate_ids = [r["candidate_id"] for r in results]
        assert len(candidate_ids) == len(set(candidate_ids)), (
            f"Duplicate candidate_ids found: {candidate_ids}"
        )


# ===================================================================
# 6. Full Resume Retrieval Tests
# ===================================================================


class TestGetFullResume:
    def test_get_full_resume_returns_text(
        self, retriever: ResumeRetriever, indexed_store: object
    ) -> None:
        """get_full_resume should return non-empty text for a known candidate."""
        # First, find a candidate_id
        results = retriever.search("React developer", top_k=1)
        assert len(results) >= 1
        candidate_id = results[0]["candidate_id"]

        full_text = retriever.get_full_resume(candidate_id)
        assert full_text is not None
        assert len(full_text) > 100, "Full resume text too short"

    def test_get_full_resume_contains_key_info(
        self, retriever: ResumeRetriever, indexed_store: object
    ) -> None:
        """The full resume should contain the candidate's key skills."""
        # Find Alice (React developer)
        results = retriever.search("React developer", top_k=1)
        candidate_id = results[0]["candidate_id"]
        full_text = retriever.get_full_resume(candidate_id)

        assert "React" in full_text, "React skill not found in full resume"
        assert "Alice" in full_text or "ALICE" in full_text, "Name not in full resume"

    def test_get_full_resume_nonexistent(self, retriever: ResumeRetriever) -> None:
        """Nonexistent candidate_id should return None."""
        result = retriever.get_full_resume("nonexistent_candidate_12345")
        assert result is None


# ===================================================================
# 7. Candidate Listing Tests
# ===================================================================


class TestCandidateListing:
    def test_get_all_candidate_ids(
        self, retriever: ResumeRetriever, indexed_store: object
    ) -> None:
        """Should return exactly 4 unique candidate IDs."""
        ids = retriever.get_all_candidate_ids()
        assert len(ids) == 4, f"Expected 4 candidates, got {len(ids)}"

    def test_candidate_ids_are_strings(
        self, retriever: ResumeRetriever, indexed_store: object
    ) -> None:
        """All candidate IDs should be non-empty strings."""
        ids = retriever.get_all_candidate_ids()
        for cid in ids:
            assert isinstance(cid, str)
            assert len(cid) > 0


# ===================================================================
# 8. Integration: Ingest Script Checkpoint
# ===================================================================


class TestIngestionCheckpoint:
    def test_checkpoint_command_format(
        self, all_sample_pdfs: list[Path], temp_chroma_dir: Path
    ) -> None:
        """Replicate the exact checkpoint command from implementation-plan.md."""
        collection = reset_collection(temp_chroma_dir)
        from src.rag.indexer import ResumeIndexer

        indexer = ResumeIndexer()
        stats = indexer.ingest_directory(FIXTURES_DIR, collection)

        retriever = ResumeRetriever(collection)
        results = retriever.search("React developer", top_k=3)

        assert len(results) >= 1
        # Print in the format expected by the checkpoint command
        for r in results:
            assert "name" in r
            assert "score" in r
            print(f'  - {r["name"]} (score: {r["score"]:.3f})')